{"trial_id": "05", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "filters", "default": null, "conditions": [], "min_value": 32, "max_value": 128, "step": 32, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "kernel_size", "default": 3, "conditions": [], "values": [3, 5], "ordered": true}}, {"class_name": "Float", "config": {"name": "dropout", "default": 0.3, "conditions": [], "min_value": 0.3, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_fc", "default": 0.3, "conditions": [], "min_value": 0.3, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001], "ordered": true}}, {"class_name": "Float", "config": {"name": "dropout_rate", "default": 0.3, "conditions": [], "min_value": 0.3, "max_value": 0.5, "step": 0.1, "sampling": "linear"}}], "values": {"filters": 128, "kernel_size": 5, "dropout": 0.3, "dropout_fc": 0.5, "learning_rate": 0.001, "dropout_rate": 0.3}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 120, in _build_wrapper\n    return self._build(hp, *args, **kwargs)\n  File \"C:\\Users\\0871\\AppData\\Local\\Temp\\ipykernel_3200\\748356566.py\", line 13, in build\n    model.add(Conv1D(filters=hp.Int('filters', min_value=32, max_value=128, step=32),\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras\\src\\models\\sequential.py\", line 121, in add\n    self._maybe_rebuild()\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras\\src\\models\\sequential.py\", line 140, in _maybe_rebuild\n    self.build(input_shape)\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras\\src\\layers\\layer.py\", line 226, in build_wrapper\n    original_build_method(*args, **kwargs)\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras\\src\\models\\sequential.py\", line 186, in build\n    x = layer(x)\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\0871\\.conda\\envs\\colab\\lib\\site-packages\\keras\\src\\ops\\operation_utils.py\", line 221, in compute_conv_output_shape\n    raise ValueError(\nValueError: Computed output size would be negative. Received `inputs shape=(None, 1, 128)`, `kernel shape=(5, 128, 128)`, `dilation_rate=[1]`.\n"}